<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WpfPerfBench.Core\WpfPerfBench.Core.csproj" />
    <ProjectReference Include="..\WpfPerfBench.Data\WpfPerfBench.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\" />
    <Folder Include="Views\" />
  </ItemGroup>

</Project>
