<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icons\wpb.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\cabinet.png" />
    <None Remove="Resources\Icons\dark.png" />
    <None Remove="Resources\Icons\email.png" />
    <None Remove="Resources\Icons\empty.png" />
    <None Remove="Resources\Icons\geer.png" />
    <None Remove="Resources\Icons\info.png" />
    <None Remove="Resources\Icons\key_lock.png" />
    <None Remove="Resources\Icons\light.png" />
    <None Remove="Resources\Icons\link.png" />
    <None Remove="Resources\Icons\lock.png" />
    <None Remove="Resources\Icons\man.png" />
    <None Remove="Resources\Icons\success.png" />
    <None Remove="Resources\Icons\warning.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\cabinet.png">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\cross_mark.png">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\dark.png" />
    <Resource Include="Resources\Icons\email.png">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\empty.png" />
    <Resource Include="Resources\Icons\geer.png" />
    <Resource Include="Resources\Icons\info.png" />
    <Resource Include="Resources\Icons\key_lock.png" />
    <Resource Include="Resources\Icons\light.png" />
    <Resource Include="Resources\Icons\link.png" />
    <Resource Include="Resources\Icons\lock.png" />
    <Resource Include="Resources\Icons\man.png" />
    <Resource Include="Resources\Icons\success.png" />
    <Resource Include="Resources\Icons\warning.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\wpb.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="H.Hooks" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WpfPerfBench.Core\WpfPerfBench.Core.csproj" />
    <ProjectReference Include="..\WpfPerfBench.Data\WpfPerfBench.Data.csproj" />
  </ItemGroup>

</Project>
